# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # CPU configuration
  nixpkgs.hostPlatform = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = true;

  # File systems configuration
  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

  # Swap configuration for 8GB RAM
  swapDevices = [ 
    { device = "/dev/disk/by-label/swap"; }
  ];

  # Memory configuration
  hardware.enableAllFirmware = true;
  hardware.enableRedistributableFirmware = true;

  # Power management
  powerManagement.enable = true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";

  # Hardware specific settings for Dell Inspiron 5548
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;  # Needed for Steam and some games
    extraPackages = with pkgs; [
      intel-media-driver  # VAAPI driver for Intel iGPU
      vaapiIntel         # Intel VA-API support
      rocm-opencl-icd    # OpenCL support for AMD
      rocm-opencl-runtime
      amdvlk             # Vulkan support for AMD
      xorg.xf86videoamdgpu  # AMD graphics driver
    ];
    extraPackages32 = with pkgs.pkgsi686Linux; [  # 32-bit support
      libva
      vaapiVdpau
      libvdpau-va-gl
    ];
  };

  # AMD graphics settings
  services.xserver.videoDrivers = [ "amdgpu" "radeon" ];  # Both drivers for compatibility
  hardware.enableRedistributableFirmware = true;  # For AMD firmware

  # Power management for hybrid graphics
  hardware.bumblebee.enable = true;  # For hybrid Intel/AMD setup
  hardware.bumblebee.group = "video";

  # Touchpad configuration
  services.xserver.libinput = {
    enable = true;
    touchpad = {
      naturalScrolling = true;
      tapping = true;
      disableWhileTyping = true;
    };
  };

  # Webcam support
  hardware.webcam.enable = true;

  # Intel specific settings
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Network interfaces
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  # High DPI settings if needed
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
